apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override namespace
namespace: harbor-operator-ns

# Common annotations
commonAnnotations:
  goharbor.io/deploy-engine: Kustomization
  goharbor.io/deploy-mode: cluster
  goharbor.io/operator-version: v1.0.0

# All the referred deployment manifests
# NOTES: when doing changes to the ref versions, please also do same changes in the patch/annotation.yaml file
resources:
  - ../../config/default
  - https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml?ref=v1.0.0
  - github.com/zalando/postgres-operator/manifests?ref=v1.5.0
  - github.com/minio/operator?ref=v3.0.13

# If you have to override the image path, uncomment this patch and also change the image paths in the patch/patches-images.yaml file.
# Then rebuild.
# patchesStrategicMerge:
# - patch/images.yaml

patchesJson6902:
  - path: patch/namespace.yaml
    target:
      kind: Namespace
      name: minio-operator
      version: v1
  - path: patch/annotations.yaml
    target:
      group: apps
      kind: Deployment
      name: harbor-operator
      version: v1

images:
  - name: quay.io/spotahome/redis-operator
    newName: quay.io/spotahome/redis-operator
    newTag: v1.0.0
  - name: goharbor/harbor-operator
    newName: goharbor/harbor-operator
    newTag: dev_develop
